climacolandia/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'climacolandia.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('orders.urls'))
)

orders/urls.py
from django.conf.urls import patterns, include, url
from orders import views
from views import MakeOrder

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^pedir/$', MakeOrder.as_view(), name='order'),
	url(r'^contato/$', views.call, name='call'),
	url(r'^gerenciar/$', views.manage, name='manage'),
	url(r'^pedido/(?P<order_id>\d+)&', views.show, name='show'),
	url(r'^pedido_concluido/(?P<order_id>\d+)&', views.show_concluded, name='show_concluded'),
	url(r'^conclude/(?P<order_id>\d+)&', views.conclude, name='conclude'),
	url(r'^exclude/(?P<order_id>\d+)&', views.exclude, name='exclude')
)

orders/models.py
from django.db import models

class Order(models.Model):
	type_sweet = models.CharField(max_length=255, null=False)
	description = models.TextField(null=False)

	def conclude(self):
		order_concluded = OrdersConcluded(type_sweet=self.type_sweet, 
			description=self.description)
		order_concluded.save()
		self.delete()

	def exclude(self):
		self.delete()

class OrdersConcluded(models.Model):
	type_sweet = models.CharField(max_length=255, null=False)
	description = models.TextField(null=False)

orders/forms.py
from django import forms

class MakeOrderForm(forms.Form):
	type_sweet = forms.CharField(required=True)
	description = forms.CharField(required=True)

	def is_valid(self):
		valid = True

		if not super(MakeOrderForm, self).is_valid():
			self.add_error('Por favor, preencha todos os campos')
			valid = False

		return valid

	def add_error(self, error_message):
		errors_in_form = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
		errors_in_form.append(error_message)

orders/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from orders.forms import MakeOrderForm
from orders.models import Order, OrdersConcluded

def index(request):
	return render(request, 'index.html')

def call(request):
	return render(request, 'call.html')

def manage(request):
	return render(request, 'manage.html', { 'orders' : Order.objects.all(), 'orders_concluded' : OrdersConcluded.objects.all() })

def conclude(request, order_id):
	order = Order.objects.get(id=order_id)
	order.conclude()
	return redirect('manage')

def show(request, order_id):
	order = Order.objects.get(id=order_id)
	already_concluded = order in OrdersConcluded.objects.all()
	return render(request, 'show.html', { 'order' : order , 'already_concluded' : already_concluded })

def show_concluded(request, order_id):
	order = OrdersConcluded.objects.get(id=order_id)
	already_concluded = order in OrdersConcluded.objects.all()
	return render(request, 'show.html', { 'order' : order , 'already_concluded' : already_concluded })


def exclude(request, order_id):
	order = Order.objects.get(id=order_id)
	order.exclude()
	return redirect('manage')

class MakeOrder(View):
	template_name = 'make_order.html'

	def get(self, request):
		return render(request, self.template_name)

	def post(self, request):
		form = MakeOrderForm(request.POST)

		if form.is_valid():
			data_from_form = form.data

			order = Order(type_sweet=data_from_form['type_sweet'],
							description=data_from_form['description'])

			order.save()

			return redirect('call')

		return render(request, self.template_name, { 'form' : form })

orders/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <title>Climacolândia</title>
        <link href="{% static "styles/bootstrap.css" %}" rel="stylesheet">
        <link href="{% static "styles/main.css" %}" rel="stylesheet">
        <link href="{% static "img/circular.png" %}" rel="icon">
    </head>
    <body>
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v2.8&appId=1643538205943620";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>
        <div class="container">
            <nav>
                <div class="header">
                    <ul class="nav nav-pills pull-right">
                        <li class=""><a href="{% url 'index' %}">Nossos Trabalhos</a></li>
                        <li class=""><a href="{% url 'order' %}">Faça um pedido</a></li>
                    </ul>
                    <h3 class="text-muted"><a href="{% url 'index' %}">
                        <img width="75" src="{% static "img/circular.png" %}">
                        Climacolândia Doces
                    </a></h3>
                </div>
            </nav>

            <div class="row content">
                {% block body%}
                {% endblock %}
            </div>
        </div>
    </body>
</html>

orders/templates/base_manage.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <title>Climacolândia</title>
        <link href="{% static "styles/bootstrap.css" %}" rel="stylesheet">
        <link href="{% static "styles/main.css" %}" rel="stylesheet">
        <link href="{% static "img/circular.png" %}" rel="icon">
    </head>
    <body>
        <div class="container">
            <nav>
                <div class="header">
                    <ul class="nav nav-pills pull-right">
                        <li class=""><a href="{% url 'manage' %}">Gerenciar Pedidos</a></li>
                    </ul>
                    <h3 class="text-muted"><a href="{% url 'index' %}">
                        <img width="75" src="{% static "img/circular.png" %}">
                        Climacolândia Doces
                    </a></h3>
                </div>
            </nav>

            <div class="row content">
                {% block body%}
                {% endblock %}
            </div>
        </div>
    </body>
</html>

orders/templates/call.html
{% extends "base.html" %}
{% block body %}
<h2 class="form-signin-heading">Agora entre em contato conosco :)</h2>
<p>Nos ligue ou mande uma mensagem por meio do número (61) 98180-2394</p>
{% endblock %}

orders/templates/index.html
{% extends "base.html" %}
{% block body %}
<div class="col-lg-12">
		<h2 class="form-signin-heading">Alguns dos nossos produtos</h2>
		<div class="fb-page" width=1000  style="margin-left: 15%; margin-right: -15%;" data-href="https://www.facebook.com/climacolandia/" data-tabs="timeline" data-small-header="true" data-hide-cover="true" data-show-facepile="true"><blockquote cite="https://www.facebook.com/climacolandia/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/climacolandia/">Climacolândia Doces</a></blockquote></div>
</div>
{% endblock %}	

orders/templates/make_order.html
{% extends "base.html" %}
{% block body %}
<form class="form-signin" action="{% url 'order' %}" method="post">

    {% csrf_token %}


    <div class="col-lg-12">
        <h2 class="form-signin-heading">Faça sua encomenda conosco</h2>

        <hr>

        <p>Nos diga qual doce você quer! Como por exemplo: Bolo, bombom, alfajor, docinhos, etc.</p>
        <input type="text" id="id_type_sweet" name="type_sweet" class="form-control" placeholder="Qual doce você quer? :)" value="{{form.type_sweet.value}}" required autofocus>

        <hr \>

        <p>Agora nos fale os detalhes do que você quer! Conte-nos por exemplo do recheio, sabor, cobertura, etc.</p>
        <textarea type="textarea" id="id_description" style="resize: none;" rows="5" name="description" class="form-control" value="{{form.description.value}}" placeholder="Conte-nos detalhes sobre o seu pedido"></textarea>
        <hr/>

        {% if form.errors %}
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Enviar Pedido</button>
    </div>

</form>
{% endblock %}

orders/templates/manage.html
{% extends "base_manage.html" %}
{% block body %}
<h2 class="form-signin-heading">Pedidos recebidos</h2>
<div class="panel panel-default">
    {% with total_orders=orders.count total_orders_concluded=orders.concluded.count %}
        {% if total_orders %}
            <div class="panel-heading">
                <strong>Você tem {{ total_orders }} pedido{{ total_orders|pluralize}} pendente{{ total_orders|pluralize}}</strong>  
            </div>
            <ul class="list-group">
                {% for order in orders.all %}
                    <li class="list-group-item">
                        <a href="{% url 'show' order.id %}">{{ order.type_sweet }}</a> 
                        <a href="{% url 'conclude' order.id %}" class="pull-right ">concluído</a><br>
                        <a href="{% url 'exclude' order.id %}" class="pull-right ">excluir</a><br>
                    </li>
                {% endfor %}
            </ul>
        {% else %}  
            <div class="panel-body">
                <p>Nenhum pedido recebido :/</p>
            </div>
        {% endif %}
    {% endwith %}
</div>

<h2 class="form-signin-heading">Pedidos concluidos</h2>
<div class="panel panel-default">
    {% with total_orders_concluded=orders_concluded.count %}
        {% if total_orders_concluded %}
            <div class="panel-heading">
                <strong>Você concluiu {{ total_orders_concluded }} pedido{{ total_orders_concluded|pluralize}}</strong>  
            </div>
            <ul class="list-group">
                {% for order in orders_concluded.all %}
                    <li class="list-group-item">
                        <a href="{% url 'show_concluded' order.id %}">{{ order.type_sweet }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}  
            <div class="panel-body">
                <p>Nenhum pedido concluido :/</p>
            </div>
        {% endif %}
    {% endwith %}
</div>
{% endblock %}

orders/templates/show.html
{% extends "base_manage.html" %}
{% block body %}
<div class="row">
	<div class="col-lg-12">
		<h2 style="margin-top: 0">Pedido de {{ order.type_sweet }}</h2>
		<address>
			<p>Descrição do pedido: {{ order.description }}</p><br>
		</address>

		{% if already_concluded %}
			<div class="well well-sm">Você já conluiu esse pedido! :)</div>
		{% else %}
        	<a href="{% url 'conclude' order.id %}" class="pull-right list-group-item">concluído</a>
            <a href="{% url 'exclude' order.id %}" class="pull-right list-group-item">excluir</a>
		{% endif %}

	</div>
</div>
{% endblock %}